# Generated by Django 5.2 on 2025-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@mail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='senha',
            field=models.CharField(default='123456', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('psicologo', 'Psicólogo')], default='paciente', max_length=20),
            preserve_default=False,
        ),
    ]
