# Generated by Django 5.2 on 2025-06-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_psychologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('objetivos', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.psychologist')),
            ],
        ),
    ]
