# Generated by Django 5.2 on 2025-06-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_therapyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.therapyplan')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.psychologist')),
            ],
        ),
    ]
