# Generated by Django 5.2 on 2025-06-19 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('boleto', 'Boleto')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data', models.DateField()),
                ('sessao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
    ]
