# Generated by Django 5.2 on 2025-06-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologistSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specialty')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.psychologist')),
            ],
        ),
    ]
